# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

    - name: Print PAT and Environment Variables
      env:
        GEN: ${{ secrets.GEN }}
      run: |
        echo "Personal Access Token (PAT): $GEN"
        env | grep GEN  # Print environment variables containing GEN



        
    - name: Verify Permissions
      env:
        GEN: ${{ secrets.GEN }} # Assuming PAT is stored as a secret
      run: |
        git clone https://$GEN@github.com/magdamd/testGitHub.git temp_repo
        cd temp_repo
        git fetch
        git log -1
      




    - name: Commit Changes
      env:
        GEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "magdamduarte@gmail.com"
        git config --global user.name "magdamd"
        git config --global credential.helper cache
        git config --global credential.helper 'cache --timeout=3600'
        git add New_version_values.txt
        git commit -m "Update New_version_values.txt"
        #git push https://$GEN@github.com/magdamd/testGitHub.git
        git config --global user.email "magdamduarte@gmail.com"
        git config --global user.name "magdamd"
        git config --global credential.helper cache
        git config --global credential.helper 'cache --timeout=3600'
        git add New_version_values.txt
        git push https://$GEN@github.com/magdamd/testGitHub.git

